### ISSUE TITLE
Alfa modifica el datos.txt y crea un archivo llamado CPUAlfa.txt con los datos de su cpu

### ISSUE THREAD

**Issue by Matias658** [Behrens0/TP_SO_i3_107#1]

**Comment by Matias658** [comment]
Pude hacer un commit, pero a la hora de hacer push me tira el siguiente error:
PS D:\Desktop\TP_SO_i3_107> git push origin Simone
remote: Permission to Behrens0/TP_SO_i3_107.git denied to Matias658.
fatal: unable to access 'https://github.com/Behrens0/TP_SO_i3_107.git/': The requested URL returned error: 403

**Comment by Martiin542** [comment]
Te olvidaste de aceptar la invitacion de colaboraldor al repo.

**Comment by Matias658** [comment]
Ahí me funcinó jaja, Graciass
